services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: allo
      MYSQL_PASSWORD: allo
      MYSQL_DATABASE: allo_hiring
    ports:
      - '4306:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -uroot -p"$$MYSQL_ROOT_PASSWORD"']
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:alpine
    ports:
      - '4379:6379'
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
